// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/ardanlabs/gotraining/grupo_de_estudio/ejemplo-go-wire/dependencias-abstractas/2-wire/event"
	"github.com/ardanlabs/gotraining/grupo_de_estudio/ejemplo-go-wire/dependencias-abstractas/2-wire/greeter"
	"github.com/ardanlabs/gotraining/grupo_de_estudio/ejemplo-go-wire/dependencias-abstractas/2-wire/message"
)

// Injectors from wire.go:

func InitializeEvent() event.Event {
	messageMessage := message.NewMessage()
	greeterGreeter := greeter.NewGreeter(messageMessage)
	eventEvent := event.NewEvent(greeterGreeter)
	return eventEvent
}
